runtime: nodejs12
service: default

handlers:
    - url: /.*
      static_files: views/index.ejx
      upload: views/index.ejs

manual_scaling: 
    instances: 1

resources:
    cpu: 2
    memory_gb: 4.0
    disk_size_gb: 20

env_variables:
    PORT: "8080"
